USE wfs;

INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (1, 'Cash');
INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (2, 'Home');
INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (3, 'Shares');
INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (4, 'Term Deposit');
INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (5, 'Managed Fund');
INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (6, 'Superannuation Fund');
INSERT INTO ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (7, 'Pension');


INSERT INTO GENDER (GENDER_ID, DESCRIPTION) VALUES (1, 'Male');
INSERT INTO GENDER (GENDER_ID, DESCRIPTION) VALUES (2, 'Female');


INSERT INTO MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (1, 'Never Married');
INSERT INTO MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (2, 'Married');
INSERT INTO MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (3, 'Separated but not Divorced');
INSERT INTO MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (4, 'Divorced');
INSERT INTO MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (5, 'Widowed');
UPDATE MARITAL_STATUS SET ACTIVE = 1;


INSERT INTO WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (1, 'Unemployed');
INSERT INTO WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (2, 'Full Time');
INSERT INTO WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (3, 'Part Time');
INSERT INTO WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (4, 'Casual');
INSERT INTO WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (5, 'Fixed Term');
