-----------------------------------------------------------------
-- Populate tables with lists for Wiseman Financial Services
-- Online Financial Advice Web App
-- (c) 2014 
-- Author: Glenn Harris (glenn.harris@gmail.com)
-- Last Modified: 22/04/2014
------------------------------------------------------------------

-- Populate ASSET_TYPES
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (1, 'Cash');
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (2, 'Home');
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (3, 'Shares');
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (4, 'Term Deposit');
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (5, 'Managed Fund');
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (6, 'Superannuation Fund');
INSERT INTO WFS.ASSET_TYPES (ASSET_TYPE_ID, DESCRIPTION) VALUES (7, 'Pension');

-- Populate GENDER
INSERT INTO WFS.GENDER (GENDER_ID, DESCRIPTION) VALUES (1, 'Male');
INSERT INTO WFS.GENDER (GENDER_ID, DESCRIPTION) VALUES (2, 'Female');

-- Populate MARITAL_STATUS
INSERT INTO WFS.MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (1, 'Never Married');
INSERT INTO WFS.MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (2, 'Married');
INSERT INTO WFS.MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (3, 'Separated but not Divorced');
INSERT INTO WFS.MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (4, 'Divorced');
INSERT INTO WFS.MARITAL_STATUS (MARITAL_STATUS_ID, DESCRIPTION) VALUES (5, 'Widowed');
UPDATE WFS.MARITAL_STATUS SET ACTIVE = 1;

-- Populate WORK_STATUS
INSERT INTO WFS.WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (1, 'Unemployed');
INSERT INTO WFS.WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (2, 'Full Time');
INSERT INTO WFS.WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (3, 'Part Time');
INSERT INTO WFS.WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (4, 'Casual');
INSERT INTO WFS.WORK_STATUS (WORK_STATUS_ID, DESCRIPTION) VALUES (5, 'Fixed Term');
