-----------------------------------------------------------------
-- Create database schema required for Wiseman Financial Services
-- Online Financial Advice Web App
-- (c) 2014 
-- Author: Glenn Harris (glenn.harris@gmail.com)
-- Last Modified: 22/04/2014
------------------------------------------------------------------

DROP TABLE WFS.CLIENTS;
DROP TABLE WFS.NAMES;
DROP TABLE WFS.CONTACTS;
DROP TABLE WFS.ASSETS;
DROP TABLE WFS.ASSET_TYPES;
DROP TABLE WFS.LIABILITIES;
DROP TABLE WFS.LIABILITY_TYPES;
DROP TABLE WFS.HEALTH_ISSUES;
DROP TABLE WFS.STATES;
DROP TABLE WFS.COUNTRIES;
DROP TABLE WFS.GENDER;
DROP TABLE WFS.MARITAL_STATUS;
DROP TABLE WFS.WORK_STATUS;

CREATE TABLE WFS.CLIENTS (
	CLIENT_ID INTEGER NOT NULL,
	NAME_ID INTEGER,
	WFS_CLIENT_NUMBER,
	PRIMARY KEY (CLIENT_ID)
);

CREATE TABLE WFS.NAMES (
	NAME_ID INTEGER NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DATE_OF_BIRTH DATE,
	GENDER INTEGER,
	MARITAL_STATUS INTEGER,
	WORK_STATUS INTEGER,
	WILL INTEGER,
	POWER_OF_ATTORNEY INTEGER,
	CONTACT_ID INTEGER,
	PRIMARY KEY (NAME_ID)
);

CREATE TABLE WFS.CONTACTS (
	CONTACT_ID INTEGER NOT NULL,
	UNIT_NUMBER INTEGER,
	STREET_NUMBER VARCHAR(10),
	STREET_NAME VARCHAR(50),
	SUBURB VARCHAR(50),
	STATE_ID INTEGER,
	COUNTRY_ID INTEGER,
	EMAIL VARCHAR(50),
	PHONE VARCHAR(20),
	PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE WFS.ASSETS (
	ASSET_ID INTEGER NOT NULL,
	ASSET_TYPE_ID INTEGER,
	ASSET_VALUE VARCHAR(20),
	PRIMARY KEY (ASSET_ID)
)

CREATE TABLE WFS.ASSET_TYPES (
	ASSET_TYPE_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(150),
	PRIMARY KEY (ASSET_TYPE_ID)
)

CREATE TABLE WFS.LIABILITIES (
	LIABILITY_ID INTEGER NOT NULL,
	LIABILITY_TYPE_ID INTEGER,
	LIABILITY_VALUE VARCHAR(20),
	PRIMARY KEY (LIABILITY_ID)
)

CREATE TABLE WFS.LIABILITY_TYPES (
	LIABILITY_TYPE_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(150)
)

CREATE TABLE WFS.INCOMES (
	INCOME_ID INTEGER NOT NULL,
	INCOME_TYPE_ID INTEGER,
	INCOME_VALUE VARCHAR(20),
	PRIMARY_KEY (INCOME_ID)
)

CREATE TABLE WFS.INCOME_TYPES (
	INCOME_TYPE_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(150)
)

CREATE TABLE WFS.HEALTH_ISSUES (
	HEALTH_ISSUE_ID INTEGER NOT NULL,
	NAME_ID INTEGER,
	DESCRIPTION VARCHAR(255),
	PRIMARY KEY (HEALTH_ISSUE_ID)
);

CREATE TABLE WFS.GENDER (
	GENDER_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(10),
	PRIMARY KEY (GENDER_ID)
);

CREATE TABLE WFS.MARITAL_STATUS (
	MARITAL_STATUS_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(20),
	ACTIVE INTEGER,
	PRIMARY KEY (MARITAL_STATUS_ID)
);

CREATE TABLE WFS.WORK_STATUS (
	WORK_STATUS_ID INTEGER NOT NULL,
	DESCRIPTION VARCHAR(20),
	PRIMARY KEY (WORK_STATUS_ID)
);




	

--ALTER TABLE WFS.CNAMES 